"""
Consistency regularization losses for semi-supervised learning.

Two complementary strategies:
  1. Mean Teacher (Tarvainen & Valpola 2017):
     - Student network trained with supervised loss + consistency w.r.t. teacher
     - Teacher weights = EMA of student weights
     - Consistency: KL divergence or MSE between student/teacher predictions
       on the SAME unlabeled input under different augmentations

  2. Pseudo-label loss (Lee 2013 + confidence thresholding):
     - Teacher generates hard pseudo-labels on unlabeled data
     - Student trained on pseudo-labels weighted by teacher confidence
     - Only high-confidence predictions are used (above threshold)
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from copy import deepcopy


# ── Mean Teacher EMA update ────────────────────────────────────────────────────

def update_ema(student: nn.Module, teacher: nn.Module, alpha: float = 0.999):
    """
    Exponential Moving Average update of teacher from student weights.
    Call this after every training step.

    α close to 1 → teacher changes slowly → more stable targets.
    Typical values: 0.99 – 0.9999.
    """
    with torch.no_grad():
        for t_param, s_param in zip(teacher.parameters(), student.parameters()):
            t_param.data.mul_(alpha).add_(s_param.data, alpha=(1.0 - alpha))

        # also update buffers (e.g. BatchNorm running stats)
        for t_buf, s_buf in zip(teacher.buffers(), student.buffers()):
            t_buf.data.copy_(s_buf.data)


def create_teacher(student: nn.Module) -> nn.Module:
    """
    Create a teacher model as a deepcopy of the student.
    Teacher parameters are NOT updated by the optimizer — only by EMA.
    """
    teacher = deepcopy(student)
    for param in teacher.parameters():
        param.requires_grad_(False)
    teacher.eval()
    return teacher


# ── Consistency loss ───────────────────────────────────────────────────────────

class MeanTeacherConsistencyLoss(nn.Module):
    """
    Consistency loss between student and teacher predictions on unlabeled data.

    Given the same unlabeled image x:
      - student_pred  = student(augment_strong(x))
      - teacher_pred  = teacher(augment_weak(x))   [no_grad]
    Loss = MSE(softmax(student_pred), softmax(teacher_pred))

    Args:
        consistency_type:  'mse' | 'kl'
            'mse' → simpler, works well in practice
            'kl'  → teacher as target distribution, can be sharper
        ramp_up_epochs:    linearly ramp up consistency weight over N epochs
                           to avoid the model collapsing early
        max_weight:        peak consistency loss weight
    """

    def __init__(
        self,
        consistency_type: str   = "mse",
        ramp_up_epochs:   int   = 40,
        max_weight:       float = 1.0,
    ):
        super().__init__()
        self.consistency_type = consistency_type
        self.ramp_up_epochs   = ramp_up_epochs
        self.max_weight       = max_weight

    def ramp_weight(self, epoch: int) -> float:
        """Sigmoid ramp-up: weight goes from 0 to max_weight over ramp_up_epochs."""
        if epoch >= self.ramp_up_epochs:
            return self.max_weight
        return self.max_weight * (epoch / self.ramp_up_epochs) ** 2

    def forward(
        self,
        student_logits: torch.Tensor,   # (B, C, H, W, D)
        teacher_logits: torch.Tensor,   # (B, C, H, W, D) — detached
        epoch:          int = 0,
    ) -> dict:
        weight = self.ramp_weight(epoch)

        student_probs = torch.softmax(student_logits, dim=1)
        teacher_probs = torch.softmax(teacher_logits.detach(), dim=1)

        if self.consistency_type == "mse":
            loss = F.mse_loss(student_probs, teacher_probs)
        elif self.consistency_type == "kl":
            # KL(teacher || student): teacher as target distribution
            loss = F.kl_div(
                F.log_softmax(student_logits, dim=1),
                teacher_probs,
                reduction="batchmean",
            )
        else:
            raise ValueError(f"Unknown consistency_type: {self.consistency_type}")

        weighted_loss = weight * loss

        return {
            "consistency_loss":         weighted_loss,
            "raw_consistency_loss":     loss.item(),
            "consistency_weight":       weight,
        }


# ── Pseudo-label loss ──────────────────────────────────────────────────────────

class PseudoLabelLoss(nn.Module):
    """
    Supervised loss on pseudo-labels generated by the teacher model.

    Algorithm:
      1. Teacher generates soft probabilities on unlabeled image
      2. Convert to hard labels: argmax over class dimension
      3. Filter out voxels where teacher confidence < threshold
      4. Compute CE loss on remaining (confident) voxels

    Args:
        confidence_threshold:  minimum teacher probability to accept as pseudo-label
                               (e.g. 0.9 → only use voxels where teacher is >90% confident)
        min_annotated_frac:    skip the batch if fewer than this fraction of voxels
                               are above the confidence threshold (avoids noisy updates)
    """

    def __init__(
        self,
        confidence_threshold: float = 0.90,
        min_annotated_frac:   float = 0.01,
    ):
        super().__init__()
        self.threshold         = confidence_threshold
        self.min_frac          = min_annotated_frac

    @torch.no_grad()
    def generate_pseudo_labels(
        self,
        teacher:        nn.Module,
        unlabeled_imgs: torch.Tensor,       # (B, 1, H, W, D)
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Generate pseudo-labels and confidence masks from teacher predictions.

        Returns:
            pseudo_labels:    (B, H, W, D) int64 — argmax class per voxel
            confident_mask:   (B, H, W, D) bool  — True where confidence > threshold
        """
        teacher.eval()
        probs = torch.softmax(teacher(unlabeled_imgs), dim=1)   # (B, C, H, W, D)
        confidence, pseudo_labels = probs.max(dim=1)             # (B, H, W, D) each

        confident_mask = confidence >= self.threshold
        return pseudo_labels, confident_mask

    def forward(
        self,
        student_logits:  torch.Tensor,   # (B, C, H, W, D)
        pseudo_labels:   torch.Tensor,   # (B, H, W, D) int64
        confident_mask:  torch.Tensor,   # (B, H, W, D) bool
    ) -> dict:
        """
        Compute CE loss only at confident voxels.
        """
        annotated_frac = confident_mask.float().mean().item()

        if annotated_frac < self.min_frac:
            # Too few confident voxels — skip to avoid noisy gradients
            zero = torch.tensor(0.0, device=student_logits.device,
                                requires_grad=True)
            return {
                "pseudo_loss":    zero,
                "annotated_frac": annotated_frac,
                "skipped":        True,
            }

        # Mask out uncertain voxels using ignore_index
        target = pseudo_labels.clone()
        target[~confident_mask] = -1   # -1 = ignore in CE

        loss = F.cross_entropy(student_logits, target, ignore_index=-1)

        return {
            "pseudo_loss":    loss,
            "annotated_frac": annotated_frac,
            "skipped":        False,
        }


# ── Combined semi-supervised loss ──────────────────────────────────────────────

class SemiSupervisedLoss(nn.Module):
    """
    Full semi-supervised loss combining:
      - Supervised loss (Dice + CE on labeled data)
      - Consistency loss (Mean Teacher on unlabeled data)
      - Pseudo-label loss (optional, on unlabeled data)

    Args:
        supervised_loss:    nn.Module — DiceCECombined or TumorFocusedLoss
        use_pseudo_labels:  whether to include pseudo-label loss
        consistency_weight: max weight for consistency loss (ramped up)
        pseudo_weight:      weight for pseudo-label loss
    """

    def __init__(
        self,
        supervised_loss:   nn.Module,
        use_pseudo_labels: bool  = True,
        consistency_weight: float = 1.0,
        pseudo_weight:     float = 0.5,
        confidence_threshold: float = 0.90,
        ramp_up_epochs:    int   = 40,
    ):
        super().__init__()
        self.supervised_loss   = supervised_loss
        self.consistency_loss  = MeanTeacherConsistencyLoss(
            max_weight=consistency_weight,
            ramp_up_epochs=ramp_up_epochs,
        )
        self.pseudo_loss_fn    = (
            PseudoLabelLoss(confidence_threshold=confidence_threshold)
            if use_pseudo_labels else None
        )
        self.pseudo_weight     = pseudo_weight

    def forward(
        self,
        student_labeled_logits:   torch.Tensor,   # (B, C, H, W, D)
        labels:                   torch.Tensor,   # (B, 1, H, W, D)
        student_unlabeled_logits: torch.Tensor,   # (B, C, H, W, D)
        teacher_unlabeled_logits: torch.Tensor,   # (B, C, H, W, D) — no_grad
        pseudo_labels:            torch.Tensor,   # (B, H, W, D)
        confident_mask:           torch.Tensor,   # (B, H, W, D) bool
        epoch:                    int = 0,
    ) -> dict:
        # Supervised component
        sup_result  = self.supervised_loss(student_labeled_logits, labels)

        # Consistency component
        cons_result = self.consistency_loss(
            student_unlabeled_logits, teacher_unlabeled_logits, epoch
        )

        total = sup_result["loss"] + cons_result["consistency_loss"]
        log   = {
            "loss":             total,
            "sup_loss":         sup_result["loss"].item(),
            "consistency_loss": cons_result["raw_consistency_loss"],
            "consistency_w":    cons_result["consistency_weight"],
        }

        # Pseudo-label component
        if self.pseudo_loss_fn is not None:
            pl_result = self.pseudo_loss_fn(
                student_unlabeled_logits, pseudo_labels, confident_mask
            )
            if not pl_result["skipped"]:
                total = total + self.pseudo_weight * pl_result["pseudo_loss"]
            log["pseudo_loss"]    = pl_result["pseudo_loss"].item() \
                                    if not pl_result["skipped"] else 0.0
            log["annotated_frac"] = pl_result["annotated_frac"]

        log["loss"] = total
        return log
